server:
  port: 8088
spring:
  application:
    name: spring-boot-hbase
  profiles:
    active: local

hbase:
  conf:
    properties:
      hbase:
        zookeeper:
          quorum: ''
          property:
            clientPort': '2181'
        rpc:
          timeout: '10000'
      zookeeper:
        znode:
          parent: ''